version: 2
registries:
  spark:
    type: composer-repository
    url: spark.laravel.com
    username: ${{ secrets.SPARK_USERNAME }}
    password: ${{ secrets.SPARK_API_TOKEN }}
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"

  # Maintain dependencies for Composer email-service
  - package-ecosystem: "composer"
    directory: "/email-service"
    registries:
      - spark
    schedule:
      interval: "daily"
    labels:
      - "php"
      - "dependencies"

  # Maintain dependencies for Composer email-service
  - package-ecosystem: "composer"
    directory: "/rental-service"
    registries:
      - spark
    schedule:
      interval: "daily"
    labels:
      - "php"
      - "dependencies"

  # Maintain dependencies for Composer email-service
  - package-ecosystem: "composer"
    directory: "/inventory-service"
    registries:
      - spark
    schedule:
      interval: "daily"
    labels:
      - "php"
      - "dependencies"
