version: 2
updates:
  # Maintain dependencies for Composer email-service
  - package-ecosystem: "composer"
    directory: "/email-service"
    schedule:
      interval: "daily"
    labels:
      - "php"
      - "dependencies"

  # Maintain dependencies for Composer email-service
  - package-ecosystem: "composer"
    directory: "/rental-service"
    schedule:
      interval: "daily"
    labels:
      - "php"
      - "dependencies"

  # Maintain dependencies for Composer email-service
  - package-ecosystem: "composer"
    directory: "/inventory-service"
    schedule:
      interval: "daily"
    labels:
      - "php"
      - "dependencies"
